import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

// @ts-expect-error - the server build file is generated by `remix vite:build`
// eslint-disable-next-line import/no-unresolved
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
import * as build from "~/build/server";

export const onRequest = createPagesFunctionHandler({ build });
