config:
  portfolio-infra:environment: dev
  # Cloudflare
  # pulumi config set --secret cloudflare:apiToken <token>
  # pulumi config set portfolio-infra:cloudflareAccountId <account-id>
  # pulumi config set portfolio-infra:cloudflareZoneId <zone-id>

  # TiDB Cloud
  # pulumi config set --secret portfolio-infra:tidbPublicKey <public-key>
  # pulumi config set --secret portfolio-infra:tidbPrivateKey <private-key>
  # pulumi config set portfolio-infra:tidbProjectId <project-id>

  # Redis Cloud
  # pulumi config set --secret portfolio-infra:redisApiKey <api-key>
  # pulumi config set --secret portfolio-infra:redisSecretKey <secret-key>

  # Grafana Cloud
  # pulumi config set --secret portfolio-infra:grafanaApiKey <api-key>
  # pulumi config set portfolio-infra:grafanaOrgSlug <org-slug>

  # Sentry
  # pulumi config set --secret portfolio-infra:sentryAuthToken <auth-token>
  # pulumi config set portfolio-infra:sentryOrg <org-slug>
