/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute, createRootRoute } from "@tanstack/react-router";

// Import Routes
import { Route as IndexRoute } from "./app/routes/index";

// Create Virtual Routes

const rootRoute = createRootRoute({
    component: () => <div>Root</div>,
});

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
    interface FileRoutesByPath {
        "/": {
            id: "/";
            path: "/";
            fullPath: "/";
            preLoaderRoute: typeof IndexRoute;
            parentRoute: typeof rootRoute;
        };
    }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ IndexRoute });

/* prettier-ignore-end */
