# エラー回避用
- "/===IGNORE===[\\s\\S]*?===/IGNORE===/m"
# 数字
- '/[0-9]種類/'
# 誤検知のため追加
- '方' #「カタ」が検知されてしまうため追加
- '時' #「ジ」が検知されてしまうため追加
- 'とき'
- '者' #「シャ」のときに「モノ」が検知されてしまうため追加
- 'モノ'
- 'もの'
# 定型句
- '言うは易く行うは難し'
