/* eslint-disable */
// Generated by Wrangler by running `wrangler types` (hash: e0410eb6aed49266da05709d8a1f6952)
// Runtime types generated with workerd@1.20251210.0 2025-11-17
declare namespace Cloudflare {
    interface Env {
        NODE_ENV: "production" | "development";
        DB: D1Database;
    }
}
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
interface Env extends Cloudflare.Env {}
